AccessPointControlClient/Controllers/IndividualsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using AccessPointControlClient.DTO;
using AccessPointControlClient.HttpClientHelpers;
using AccessPointControlClient.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AccessPointControlClient.Controllers
{
    [Authorize(Roles = SupportedRoles.PERSON_MANAGEMENT)]
    public class IndividualsController : Controller
    {
        //private static int COUNTER = 60;
        private static int nonFinalRegistrationValidDuration;

        private const string GET_ALL_PEOPLE = "people/all";
        private const string GET_PERSON_BY_ID = "people/{id}";
        private const string UPDATE_PERSON = "people/update";
        private const string INSERT_PERSON = "people/register";
        private const string DELETE_PERSON = "people/delete/{id}";
        private const string CLEAR_REGISTRATION = "people/clear-registration";
        private static List<SimpleIndividual> globalIndividualsList = new List<SimpleIndividual>();

        private static Individual waitingForFinalization;
        private static DateTime startOfReg;

        private readonly IHttpClient httpClient;
        public IndividualsController(IHttpClient httpClient)
        {
            this.httpClient = httpClient;
        }
        public IActionResult Individuals()
        {
            HttpResponseMessage response = httpClient.GetAsync(GET_ALL_PEOPLE);
            List<SimpleIndividual> individuals = new List<SimpleIndividual>();
            individuals = JsonConvert.DeserializeAnonymousType(response.Content.ReadAsStringAsync().Result, individuals);
            if (waitingForFinalization != null)
            {
                individuals.Add(new SimpleIndividual()
                {
                    FullName = waitingForFinalization.FullName,
                    PersonId = waitingForFinalization.PersonId,
                    RequiresImageUpload = true
                });
            }
            SortIndividualsList(individuals);

            IndividualsModel model = new IndividualsModel()
            {
                Individuals = individuals,
                SelectedIndividual = individuals.Count == 0 ? Individual.CreateEmptyIndividual() :
                GetIndividualById(individuals.First().PersonId),
                RegistrationModel = new Individual()
            };
            globalIndividualsList = model.Individuals;
            return View(model);
        }
        private Individual GetIndividualById(string id)
        {
            if (waitingForFinalization != null && waitingForFinalization.PersonId == id)
            {
                waitingForFinalization.Counter = (int)(nonFinalRegistrationValidDuration - (DateTime.Now - startOfReg).TotalSeconds);
                return waitingForFinalization;
            }
            HttpResponseMessage response = httpClient.GetAsync(GET_PERSON_BY_ID.Replace("{id}", id));
            PersonDTO personDto = null;
            personDto = JsonConvert.DeserializeAnonymousType(response.Content.ReadAsStringAsync().Result, personDto);
            return new Individual(personDto);
        }

        private void SortIndividualsList(List<SimpleIndividual> list)
        {
            list.Sort((x1, x2) => x1.FullName.CompareTo(x2.FullName));
        }

        [HttpPost]
        public IActionResult DeletePerson(IFormCollection form)
        {
            string selectedPersonId = form["selectedPersonId"];
            string newSuffix = DELETE_PERSON.Replace("{id}", selectedPersonId);
            if (waitingForFinalization == null ||
                (waitingForFinalization != null && selectedPersonId != waitingForFinalization.PersonId))
            {
                HttpResponseMessage response = httpClient.DeleteAsync(newSuffix);
            }
            return RedirectToAction(nameof(Individuals));
        }

        [HttpPost]
        public IActionResult SelectIndividual(IFormCollection form)
        {
            string selectedPersonId = form["selectedPersonId"];
            Individual selected = GetIndividualById(selectedPersonId);
            IndividualsModel model = new IndividualsModel()
            {
                Individuals = globalIndividualsList,
                RegistrationModel = new Individual(),
                SelectedIndividual = selected
            };
            return View(nameof(Individuals), model);
        }

        [HttpPost]
        public IActionResult UpdateIndividual(IndividualsModel model)
        {
            PersonDTO dtoObj = new PersonDTO(model.SelectedIndividual);
            HttpResponseMessage response = httpClient.PostAsync(UPDATE_PERSON,
                new StringContent(JsonConvert.SerializeObject(dtoObj), Encoding.UTF8, "application/json"));
            globalIndividualsList.First(x => x.PersonId == dtoObj.PersonId).FullName = dtoObj.FullName;
            SortIndividualsList(globalIndividualsList);
            Individual updatedPerson = GetIndividualById(dtoObj.PersonId);
            IndividualsModel individualsModel = new IndividualsModel()
            {
                Individuals = globalIndividualsList,
                RegistrationModel = new Individual(),
                SelectedIndividual = updatedPerson
            };

            return View(nameof(Individuals), individualsModel);
        }

        [HttpPost]
        public IActionResult RegisterIndividual(IndividualsModel model)
        {
            PersonDTO dtoObj = new PersonDTO(model.RegistrationModel);
            HttpResponseMessage response = httpClient.PostAsync(INSERT_PERSON,
                new StringContent(JsonConvert.SerializeObject(dtoObj), Encoding.UTF8, "application/json"));
            nonFinalRegistrationValidDuration = JsonConvert.DeserializeObject<int>(response.Content.ReadAsStringAsync().Result);
            //todo set nonFinalRegistrationValid
            SimpleIndividual tempInd = new SimpleIndividual() { FullName = dtoObj.FullName, RequiresImageUpload = true };
            globalIndividualsList.Add(tempInd);
            SortIndividualsList(globalIndividualsList);
            Individual newPerson = new Individual()
            {
                Counter = nonFinalRegistrationValidDuration,
                PersonId = tempInd.PersonId,
                FullName = dtoObj.FullName,
                BirthDate = dtoObj.BirthDate,
                RequiresImageUpload = true
            };
            startOfReg = DateTime.Now;
            waitingForFinalization = newPerson;
            IndividualsModel individualsModel = new IndividualsModel()
            {
                Individuals = globalIndividualsList,
                RegistrationModel = new Individual(),
                SelectedIndividual = newPerson
            };

            System.Timers.Timer timer = new System.Timers.Timer(nonFinalRegistrationValidDuration * 1000);
            timer.Elapsed += ClearPersonWaiting;
            timer.Elapsed += (src, e) => timer.Close();
            timer.Start();
            return View(nameof(Individuals), individualsModel);
        }
        public void ClearPersonWaiting(Object source, System.Timers.ElapsedEventArgs e)
        {
            if (waitingForFinalization == null)
            {
                return;
            }
            SimpleIndividual ind = globalIndividualsList.FirstOrDefault(x => x.PersonId == waitingForFinalization.PersonId);
            if (ind != null)
            {
                globalIndividualsList.Remove(ind);
            }
            waitingForFinalization = null;
        }
    }
}

AccessPointControlClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
</head>
@RenderSection("Scripts", required: false)
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm box-shadow my-navbar" id="layout-header">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <span style="float: right">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                </span>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item @(ViewContext.RouteData.Values["Controller"].ToString().Contains("Home") ? "active" : "")">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Account">
                            <img src="@Url.Content("~/images/face.png")">
                        </a>
                    </li>
                    <li class="nav-item @(ViewContext.RouteData.Values["Controller"].ToString().Contains("Individual") ? "active" : "")">
                        @Html.ActionLink("Registered individuals", "Individuals", "Individuals", new { @class = "nav-link" })
                    </li>
                    <li class="nav-item @(ViewContext.RouteData.Values["Controller"].ToString().Contains("User") ? "active" : "")">
                        @Html.ActionLink("User management", "Users", "User", new { @class = "nav-link" })
                    </li>
                    <li class="nav-item @(ViewContext.RouteData.Values["Controller"].ToString().Contains("Log") ? "active" : "")">
                        @Html.ActionLink("Logs", "Logs", "Logs", new { @class = "nav-link" })
                    </li>
                    <li class="nav-item @(ViewContext.RouteData.Values["Controller"].ToString().Contains("Debug") ? "active" : "")">
                        @Html.ActionLink("Debug", "Debug", "Debug", new { @class = "nav-link" })
                    </li>
                </ul>

            </div>
        </div>
    </nav>

    <div class="container body-content" id="body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; 2020 - WebAppProofOfConcept</p>*@
        </footer>
    </div>


</body>
</html>